<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css' rel='stylesheet'
  >
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
  <style>
    body {
      background-color: #DFE2EB !important;
      color: #222222 !important;
    }
    /*CUSTOMIZE DATATABLE UI*/
    .paginate_button {
      margin-right: 15px !important;
    }

    .page-link {
      border-radius: 5px !important;
      color: #222222;
    }
    .active>.page-link, .page-link.active {
      color: var(--bs-pagination-active-color);
      background-color: #222222 !important;
      border-color: #222222 !important;
    }


    }
  </style>
</head>
<body>

<div class="container pt-lg-4">
  <div class="row">
    <div class="col">
      <div class="card shadow-none" style="border: 2px solid #E8EBF2">
        <div class="card-body">

          <h1 class='text-dark'>Business Management System</h1>
          <p class='text-muted'>Manage all the business information in your application.</p>
          <br/>
          <table class='table table-striped table-sm small' id='datas' style='width: 100%'>
            <thead>
            <tr>
              <th scope='col'>Id</th>
              <th scope='col'>Director Name</th>
              <th scope='col'>Business Name</th>
              <th scope='col'>Business Address</th>
              <th scope='col'>Business Registration #</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($records as $record): ?>
              <tr>
                <th scope='row'><?= $record['director_id'] ?></th>
                <td><?= $record['director_name'] ?></td>
                <td><?= $record['business_name'] ?></td>
                <td><?= $record['business_address'] ?></td>
                <td><?= $record['business_registration_number'] ?></td>
              </tr>
            <?php endforeach; ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script>
  $(document).ready(function () {
    new DataTable('#datas', {
      pagingType: 'full_numbers'
    });
  })
</script>
</body>
</html>
